# This is a basic workflow to help you get started with Actions

# This is a basic workflow to help you get started with Actions

name: JENKINS-BE-CI

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  trigger-fe-jenkins:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Trigger Jenkins Job
        uses: toptal/jenkins-job-trigger-action@master
        with:
          jenkins_url: "http://94.130.228.242:8080/"
          jenkins_user: ${{ secrets.JENKINS_USER }}
          jenkins_token: ${{ secrets.JENKINS_TOKEN }}
#           proxy: ${{ secrets.JENKINS_PROXY }}
          job_name: "springboot-pipeline-template"
          job_params: |
            {
              "service_name": "sale-point-service",
              "branch": "${{ steps.extract_branch.outputs.branch }}",
              "environment": "tst"
            }
          job_timeout: "3600" # Default 30 sec. (optional)
